dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=sematext setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: etv2mKEsWRMVoga1pMy6zcaO0k7kh9BB6LwMwN10VIoATz6cLBJuUNMoZQJ/OFUjpy8zgvVeqLuaax0MMQmwlAdEwIs2qgXNgDysbydJ95RmqmDVNWMVw/g2l6QWbIcMkuPA2TTLLhkBuyRK1FJYsdYm17Ww4V9KJspk0twJCwbT5snZ2nx0awfenOQHSfTx1vS58zCFY2s+vPChQ7AdmtLMRXYRm4/iaMMRPkscdre1XGXJtY5dRbCiI+e1NkrtHXBFdBjuvvjzHx1TxuBfVbNiUk2aWa9m4l6EZQzLBl6Gb7fh6PR/WBms+NhgGUFPqYSMX6agHorYUvaL8v7Z5ZieP2I4jG5H+cnTjye4PKlYMHz3Vi3MWoNGiibSv+fOeg2HNdtlWOZKWZLwolLNWW8XYFt68PzMMwr2TQ/uQRd2b9GZdrlXr9ZciTkx/NfmrxRAJ2CUS1+7c/K5Sd2nN0elOSQIBOoP3PNSpWDOBZKz9WCmSOZ0M+/QmrpHD7r6zSl5pQaYKrm4DHIryawx8nvZAvroOZRXYsDr5hha99jOYZVsSQKoZRzikFxtuMObgWed7jaH8D7gYP/nRKpKGxF4JPTzQNwcgPndmQeXAjt21ZJ9V052RaMZVQrR2Yy5EMUqlMpuDssK+UWPS6VmsGgGCb1UblcHZvbpYCtp05A=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
